colors:
  primary:
    background: '#1d2021'
    foreground: '#fbf1c7'
  normal:
    black:   '#1d2021'
    red:     '#fe8019'
    green:   '#8ec07c'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#83a598'
    white:   '#fbf1c7'
  bright:
    black:   '#282828'
    red:     '#fe8019'
    green:   '#8ec07c'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#83a598'
    white:   '#fbf1c7'
